server:
  port: 20001
feign:
  client:
    config:
      default:
        connect-timeout: 6000
        read-timeout: 6000
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 6000